import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import { animate } from "framer-motion";
import ScrollReveal from "../components/ScrollReveal";

const LAST_UPDATED = "July 7, 2026";
const CONTACT_EMAIL = "arcc.resume@gmail.com";

// Height of the fixed site nav plus breathing room - matches the CSS
// --site-nav-scroll-offset used for native anchor scrolling.
const SCROLL_OFFSET = 90;

const SECTIONS = [
  {
    id: "what-rcc-is",
    title: "1. What RCC is",
    body: (
      <>
        <p>
          RCC (Resume &amp; Career Coach) helps you prepare for your job
          search. You can upload a resume, score it against a job description,
          see which skills you are missing, and rehearse with an AI-powered
          mock interviewer.
        </p>
        <p>
          By creating an account or using RCC, you agree to these terms. If
          you do not agree with them, please do not use the service.
        </p>
      </>
    ),
  },
  {
    id: "your-account",
    title: "2. Your account",
    body: (
      <>
        <p>
          You need an account to use the dashboard. You can sign up with an
          email address and password or with Google. You are responsible for
          keeping your credentials safe and for any activity that happens
          under your account.
        </p>
        <p>
          Sign up with accurate information and only create an account for
          yourself. We verify your email address with a one-time code before
          activating the account.
        </p>
      </>
    ),
  },
  {
    id: "your-content",
    title: "3. Your content",
    body: (
      <>
        <p>
          The resumes and job descriptions you upload remain yours. We store
          and process them only to provide the service - scoring, suggestions,
          history, and interview practice. We do not sell your content or
          share it with third parties for marketing.
        </p>
        <p>
          You can permanently delete your account and everything associated
          with it at any time from{" "}
          <em>Dashboard &gt; Settings &gt; Delete account</em>. Deletion is
          immediate and cannot be undone.
        </p>
      </>
    ),
  },
  {
    id: "ai-generated-results",
    title: "4. AI-generated results",
    body: (
      <>
        <p>
          Match scores, suggestions, and interview feedback are generated by
          AI. They are informational guidance, not professional career,
          legal, or hiring advice. AI output can be imperfect or incomplete -
          review it with your own judgment before acting on it.
        </p>
        <p>
          RCC does not guarantee interviews, offers, or any particular hiring
          outcome.
        </p>
      </>
    ),
  },
  {
    id: "acceptable-use",
    title: "5. Acceptable use",
    body: (
      <p>
        Do not misuse the service: no attempts to break, overload, or probe
        the platform, no uploading content that is unlawful or that you have
        no right to share, and no using RCC to harm others. We may suspend
        accounts that violate these rules.
      </p>
    ),
  },
  {
    id: "availability",
    title: "6. Availability",
    body: (
      <p>
        RCC is currently free to use. The service is provided &quot;as
        is&quot; and &quot;as available&quot; - we work hard to keep it fast
        and reliable, but we cannot promise uninterrupted access, and features
        may change or be discontinued as the product evolves.
      </p>
    ),
  },
  {
    id: "limitation-of-liability",
    title: "7. Limitation of liability",
    body: (
      <p>
        To the maximum extent permitted by law, RCC and its creator are not
        liable for indirect, incidental, or consequential damages arising from
        your use of the service, including decisions made based on AI-generated
        suggestions or scores.
      </p>
    ),
  },
  {
    id: "changes-to-these-terms",
    title: "8. Changes to these terms",
    body: (
      <p>
        We may update these terms as the service evolves. When we do, we will
        change the &quot;Last updated&quot; date on this page. Continuing to
        use RCC after an update means you accept the revised terms.
      </p>
    ),
  },
  {
    id: "contact",
    title: "9. Contact",
    body: (
      <p>
        Questions about these terms or your data? Email us at{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> - we read
        everything.
      </p>
    ),
  },
];

// The one in-flight scroll tween; a new click stops it so two animations
// never fight over the scroll position.
let activeScroll = null;

function scrollToSection(id) {
  const el = document.getElementById(id);
  if (!el) return;

  // Accumulate offsetTop instead of using getBoundingClientRect: sections
  // waiting on their ScrollReveal entrance carry a translateY transform, which
  // would skew a rect-based measurement and make the scroll overshoot.
  let top = 0;
  for (let node = el; node; node = node.offsetParent) {
    top += node.offsetTop;
  }
  const target = top - SCROLL_OFFSET;

  if (activeScroll) activeScroll.stop();

  if (window.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches) {
    window.scrollTo({ top: target, behavior: "auto" });
    return;
  }

  // Drive the scroll with a framer-motion tween (same easing as the site's
  // card animations) so the page glides down instead of jumping. Each frame
  // scrolls with behavior:"instant" so the CSS scroll-behavior:smooth on
  // <html> doesn't fight the tween.
  const start = document.scrollingElement
    ? document.scrollingElement.scrollTop
    : window.scrollY;
  activeScroll = animate(start, target, {
    duration: 0.9,
    ease: [0.22, 1, 0.36, 1],
    onUpdate: (v) => window.scrollTo({ top: v, behavior: "instant" }),
    onComplete: () => {
      activeScroll = null;
    },
  });
}

const TermsPage = () => {
  useEffect(() => {
    const hash = window.location.hash.replace("#", "");
    if (hash && SECTIONS.some((s) => s.id === hash)) {
      // Deep link (e.g. /terms#contact): give the page a beat to lay out,
      // then glide to the requested section.
      const t = setTimeout(() => scrollToSection(hash), 150);
      return () => clearTimeout(t);
    }
    window.scrollTo(0, 0);
  }, []);

  const handleTocClick = (e, id) => {
    e.preventDefault();
    window.history.replaceState(null, "", `#${id}`);
    scrollToSection(id);
  };

  return (
    <div className="legal-page">
      <ScrollReveal>
        <header className="legal-page__head">
          <p className="eyebrow">Legal</p>
          <h1 className="legal-page__title">Terms of Service</h1>
          <p className="legal-page__updated">Last updated: {LAST_UPDATED}</p>
          <p className="legal-page__intro">
            The short version: be honest, keep your account safe, your resumes
            stay yours, and treat AI suggestions as guidance - not gospel. The
            details are below, in plain English.
          </p>
        </header>
      </ScrollReveal>

      <ScrollReveal>
        <nav className="legal-toc" aria-label="Table of contents">
          <h2 className="legal-toc__title">On this page</h2>
          <ol className="legal-toc__list">
            {SECTIONS.map((section, i) => (
              <li key={section.id}>
                <a
                  href={`#${section.id}`}
                  className="legal-toc__link"
                  onClick={(e) => handleTocClick(e, section.id)}
                >
                  <span className="legal-toc__num">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span className="legal-toc__label">
                    {section.title.replace(/^\d+\.\s*/, "")}
                  </span>
                </a>
              </li>
            ))}
          </ol>
        </nav>
      </ScrollReveal>

      {SECTIONS.map((section) => (
        <ScrollReveal key={section.id}>
          <section id={section.id} className="legal-page__section">
            <h2 className="legal-page__section-title">{section.title}</h2>
            <div className="legal-page__body">{section.body}</div>
          </section>
        </ScrollReveal>
      ))}

      <ScrollReveal>
        <div className="legal-page__footer">
          <Link to="/" className="legal-page__back">
            &larr; Back to home
          </Link>
        </div>
      </ScrollReveal>
    </div>
  );
};

export default TermsPage;
